### ISSUE TITLE
Laravel Pint not working with Sail?

### ISSUE THREAD

**Issue by Quaap70** [open-southeners/vscode-laravel-pint#10]
I'm using Laravel Sail for development. Installed the plugin and de Laravel Package, but somehow it doesn't work. (VSCode on Mac M1) Any suggestions?

**Comment by d8vjork** [comment]
Do you have access to `vendor/bin/pint`? Can you run that command from your local machine?

**Comment by Quaap70** [comment]
in VSCode Output it says:
`Formatting file "app/Models/Activity.php" using command "/Users/xxxx/xxxx/vendor/bin/pint app/Models/Activity.php --preset laravel"`

But the file is not updated.

I tried it from the terminal, as stated in the original Pint documentation, and it did work. But of course it's much more convenient if it happens automatically when saving the file in VSCode.

**Comment by Quaap70** [comment]
cmd + click the `/Users/xxxx/xxxx/vendor/bin/pint` part opens the **Pint** file, so the plugin has access.

**Comment by Quaap70** [comment]
For your information

With sail I have to use:
`sail php ./vendor/bin/pint`

The command as stated in de Pint documentation:
`./vendor/bin/pint`
won't work

**Comment by d8vjork** [comment]
But is true, that I could actually add a sail option to the extension now that I think on this

**Comment by Quaap70** [comment]
I wasn't trying to suggest it was a plugin issue, it probably works just fine.  😉 Hence the question whether it also works with Sail.  Perhaps I should have asked this question elsewhere.  But I really appreciate you looking into it!

if a Sail checkbox is a possibility, that would be perfect.

**Comment by d8vjork** [comment]
@Quaap70 Tried already on a new Laravel installation using Sail on my Mac, no problem with it

Perhaps could you send here the output of that `vendor/bin/pint`? That will help a lot

**Comment by Quaap70** [comment]
Do you mean this terminal output?  

```
  FAIL   ................................................... 120 files, 5 errors, 11 style issues
  ! app/Actions/Fortify/CreateNewUser.php file_get_contents(/var/www/html/pint.json): Failed to op…
  ⨯ app/Exceptions/Handler.php                                  no_empty_statement, ordered_imports
  ⨯ app/Providers/AppServiceProvider.php                                          no_unused_imports
  ⨯ app/Providers/AuthServiceProvider.php                                           ordered_imports
  ⨯ app/Providers/EventServiceProvider.php                                          ordered_imports
  ⨯ app/Providers/RouteServiceProvider.php                                          ordered_imports
  ! app/Traits/RecordsActivity.php file_get_contents(/var/www/html/pint.json): Failed to open stre…
  ! database/migrations/2014_10_12_000000_create_users_table.php file_get_contents(/var/www/html/p…
  ⨯ database/migrations/2022_05_30_151754_create_projects_table.php class_definition, braces, orde…
  ⨯ database/migrations/2022_06_05_180508_create_tasks_table.php class_definition, braces, ordered…
  ⨯ database/migrations/2022_06_13_092552_create_activities_table.php class_definition, braces, or…
  ⨯ tests/Feature/PasswordConfirmationTest.php                                    no_unused_imports
  ! tests/Feature/PasswordResetTest.php file_get_contents(/var/www/html/pint.json): Failed to open…
  ⨯ tests/Feature/RegistrationTest.php unary_operator_spaces, not_operator_with_successor_space, o…
  ! tests/Feature/TriggerActivityTest.php file_get_contents(/var/www/html/pint.json): Failed to op…
  ⨯ tests/Unit/UserTest.php
```

By selecting the output I now see some extra information. The script searches locally for the pint.json file, which obviously isn't there. He should look for this in the project Root folder, right?  I assume it uses default values ​​then?

Could it be that it works for you because pint **can** fall back on local environment?  Which in my case is not there?

**Comment by Quaap70** [comment]
@d8vjork thanks for taking the time and effort to look into this.  I'll keep an eye on the links you mentioned for possible solutions.

**Comment by d8vjork** [comment]
Ah, much better now!

I'll close this as soon as I release the integration support, could be helpful to someone I guess

**Comment by d8vjork** [comment]
Publishing this should be in the v0.5.0

**Comment by Quaap70** [comment]
@d8vjork Thanks it's working now 👍
