### ISSUE TITLE
Executable not readable or lacks permissions for Laravel Pint.

### ISSUE THREAD

**Issue by fylzero** [open-southeners/vscode-laravel-pint#11]
Tried installing the extension.  I'm using Pint in a local project so I left the executable path alone.

Seeing the following error when saving a file in VS Code:

> Executable not readable or lacks permissions for Laravel Pint.

**Comment by fylzero** [comment]
Figured it out.  Using a non-standard directory setup due to Docker.  Just needed to change the config/executable path.

**Comment by olivsinz** [comment]
Still having this error.

I'm using Laragon, PHP8.1
