### ISSUE TITLE
Something went wrong! Executable does not exists or lacks permissions with v0.7.2

### ISSUE THREAD

**Issue by joostdebruijn** [open-southeners/vscode-laravel-pint#15]
After upgrading to v0.7.2 of this extension, I get the error "Something went wrong! Executable does not exists or lacks permissions." for manual or automatic formatting on save. Downgrading the plugin back to v0.7.1 solves this problem, without any additional modifications to the settings or the executable.

The executable is on it's default location (./vendor/bin/pint) and the permissions are looking okay.

Running with Pint v0.2.3.

**Comment by ashleyevans** [comment]
I can confirm I'm seeing this behaviour too, 0.7.2 stopped the automatic formatting on save, reverting to 0.7.1 fixed it for me too

**Comment by d8vjork** [comment]
Didn't see this coming but actually this should be regression from a3b67a5ef1cb4126d5605f062861c62deda3fbf5

Thanks for reporting!

**Comment by d8vjork** [comment]
Releasing v0.7.3 which fixes this

**Comment by jesusferm** [comment]
I have the same error in versión v0.7.3 on windows, but en linux/fedora it's working, in windows only work with command, but not on save document

**Comment by d8vjork** [comment]
@jesusferm Interesting.. can you send more details? Like what version of Laravel Pint you've and what is returning VS Code in the Output tab (selecting Laravel Pint in the selector on the right corner):

<img width="1636" alt="image" src="https://user-images.githubusercontent.com/2331052/180502426-1c5bf858-16b0-46e1-a02f-9bfe24da19a1.png">

**Comment by jesusferm** [comment]
![image](https://user-images.githubusercontent.com/5892507/180502769-5ebccc77-c5f5-440e-acd2-84288347e302.png)

This is the message output, 

en config a use extensions:
vendor/bin/pint

i tried with this path on windows:
./vendor/bin/pint
vendor/bin/pint.bat

not working

**Comment by d8vjork** [comment]
Ah! interesting, I'll move this to a new issue instead of reopening this then as its quite special to Windows OS
