### ISSUE TITLE
Formatting breaks blade markdown email files

### ISSUE THREAD

**Issue by tcampbPPU** [open-southeners/vscode-laravel-pint#17]
## Issue
I believe there might be some issues with formatting on markdown email blade files. Which according to the [docs](https://laravel.com/docs/9.x/mail#writing-markdown-messages) explain to not add excess indentation.

To recreate this issue you can build an example Mail with the example from Laravel
```bash
php artisan make:mail OrderShipped --markdown=emails.orders.shipped
```
Which should give you a blade file like so:
```php
@component('mail::message')
# Order Shipped
 
Your order has been shipped!
 
@component('mail::button', ['url' => $url])
View Order
@endcomponent
 
Thanks,<br>
{{ config('app.name') }}
@endcomponent
```
Now I have the following VSCode settings:
```json
{
    "editor.formatOnSave": true,
    "[vue]": {
        "editor.defaultFormatter": "esbenp.prettier-vscode"
    },
    "[javascript]": {
        "editor.defaultFormatter": "esbenp.prettier-vscode"
    },
    "[typescript]": {
        "editor.defaultFormatter": "esbenp.prettier-vscode"
    },
    "[php]": {
        "editor.defaultFormatter": "open-southeners.laravel-pint",
        "editor.formatOnSave": true
    }
}
```
So when I save that file is gets formatted as so
```php
@component('mail::message')
    # Introduction

    The body of your message.

    @component('mail::button', ['url' => ''])
        Button Text
    @endcomponent

    Thanks,<br>
    {{ config('app.name') }}
@endcomponent
```
Which causes the email to look a little like
![image](https://user-images.githubusercontent.com/25044744/179317577-6320284a-d7d4-4ad9-b318-7fe1d72da576.png)

## Current Workaround
Right now my workaround is to add back my previous formatter, or turn off complelty for those blade type files
```json
    "[blade]": {
        "editor.defaultFormatter": "valeryanm.vscode-phpsab",
        "editor.formatOnSave": true
    },
```

**Comment by d8vjork** [comment]
Yeah, I believe this could be an issue on Pint itself and not this extension.

You can also exclude those files from being formatted on the pint.json file

Btw didn't know that but I think this extension doesn't contribute to formatters

**Comment by tcampbPPU** [comment]
I'm not sure its Pint itself since that does not happen to that file when running `vendor/bin/pint` by itself.

**Comment by d8vjork** [comment]
What are the versions you're using of the extension and pint? Are you using any custom Pint config? 

I'm trying locally on my project but I'm unable to replicate this issue

**Comment by d8vjork** [comment]
Try adding `"editor.formatOnSave": false` and removing `editor.defaultFormatter` from the PHP part, as this extension doesn't contribute to formatters (it does the logic internally)

**Comment by tcampbPPU** [comment]
The formatter works fine for me on all other PHP files. My workaround it just to not have it format blade files so I added
```json
"[blade]": {
    "editor.defaultFormatter": "valeryanm.vscode-phpsab",
    "editor.formatOnSave": true
},
```
Which `valeryanm.vscode-phpsab` was the original formatter I was using for PHP/Blade files along side with my custom `phpcs.xml` rule set.

I guess alternatively you could just do:
```json
"[blade]": {
    "editor.defaultFormatter": "open-southeners.laravel-pint",
    "editor.formatOnSave": false
},
```

**Comment by d8vjork** [comment]
@tcampbPPU Can you try with the v1?

Is a pre-release from now as it changes a lot of out-of-the-box stuff but fixes a lot more and changes the way the extension works (now as a proper VSCode formatter)

**Comment by tcampbPPU** [comment]
Yup when using that version `v1.0.2` I am not facing that markdown blade issue as before

**Comment by d8vjork** [comment]
Great! So this can be solved, feel free to open any other issue with that specific version
