### ISSUE TITLE
Binary permissions issue on Windows

### ISSUE THREAD

**Issue by d8vjork** [open-southeners/vscode-laravel-pint#18]
![image](https://user-images.githubusercontent.com/5892507/180502769-5ebccc77-c5f5-440e-acd2-84288347e302.png)

This is the message output, 

in config a use extensions:
vendor/bin/pint

i tried with this path on windows:
./vendor/bin/pint
vendor/bin/pint.bat

not working in windows.

In linux only i use
vendor/bin/pint

update:

if i use tha absolute from C\....\laravel-project\vendor\bin\pint.bat 

then its works

_Originally posted by @jesusferm in https://github.com/open-southeners/vscode-laravel-pint/issues/15#issuecomment-1192841549_

**Comment by serdartaylan** [comment]
benzer bir eklenti ile aynı sorun, belki oradaki örnek çözüm için yardımcı olabilir.

https://github.com/msamgan/vscode-larapint/issues/18

**Comment by serdartaylan** [comment]
same problem with a similar plugin, maybe the example there can help for the solution.

https://github.com/msamgan/vscode-larapint/issues/18

**Comment by msamgan** [comment]
i have resolved it in https://github.com/msamgan/vscode-larapint
its up and running now...

**Comment by d8vjork** [comment]
@jesusferm can you try on v1.0.0? Its a pre-release so you will need to install it switching to prereleases

**Comment by serdartaylan** [comment]
![image](https://user-images.githubusercontent.com/1150010/182684349-2d14a565-9746-4d9c-b040-89c59c53d039.png)


my config
{
    "laravel-pint.enable": true,
    "laravel-pint.preset": "laravel",
    "[php]": {
        "editor.defaultFormatter": "open-southeners.laravel-pint"
    },
    "laravel-pint.enableDebugLogs": true,
    "editor.formatOnSave": true,
}

When I save the file or click on the "format document" menu, it gives the following warning. but the "pint" operation is not happening. not working
```
["INFO" - 21:41:08] Extension Name: dev.laravel-pint.
["INFO" - 21:41:08] Extension Version: 0.0.0.
["DEBUG" - 21:41:13] Enabling Laravel Pint for workspace c:\Users\st\code\laravel\api
["DEBUG" - 21:41:14] Formatting using command "c:\Users\st\code\laravel\api\vendor\bin\pint --config pint.json --preset laravel c:\Users\st\code\laravel\api\app\Console\Kernel.php"
["INFO" - 21:41:14] Formatting completed in 970ms.
```





commands I tested in terminal

**git-bash**
_working commands_
```
vendor/bin/pint --config pint.json --preset laravel c:/Users/st/code/laravel/api/app/Console/Kernel.php
vendor/bin/pint --config pint.json --preset laravel app/Console/Kernel.php
```

_not working commands_
```
vendor/bin/pint --config pint.json --preset laravel c:\Users\st\code\laravel\api\app\Console\Kernel.php
vendor/bin/pint --config pint.json --preset laravel app\Console\Kernel.php
```

**windows command prompt**
_working commands_
```
php vendor/bin/pint --config pint.json --preset laravel c:/Users/st/code/laravel/api/app/Console/Kernel.php
php vendor/bin/pint --config pint.json --preset laravel app/Console/Kernel.php
php vendor/bin/pint --config pint.json --preset laravel c:\Users\st\code\laravel\api\app\Console\Kernel.php
php vendor/bin/pint --config pint.json --preset laravel app\Console\Kernel.php
```

_not working commands_
```
vendor/bin/pint --config pint.json --preset laravel c:/Users/st/code/laravel/api/app/Console/Kernel.php
vendor/bin/pint --config pint.json --preset laravel app/Console/Kernel.php
vendor/bin/pint --config pint.json --preset laravel c:\Users\st\code\laravel\api\app\Console\Kernel.php
vendor/bin/pint --config pint.json --preset laravel app\Console\Kernel.php
```

**Comment by serdartaylan** [comment]
I did this with the help of another plugin.
https://marketplace.visualstudio.com/items?itemName=emeraldwalk.RunOnSave
I installed this plugin and applied the following settings. When I save the file RunOnSave kicks in and formats my file.

{
    "runOnSave.commands": [
        {
            "match": ".*\\.php$",
            "runIn": "backend",
            "async":true,
            "command": "php vendor/bin/pint ${fileRelative}",
            "runningStatusMessage": "${fileBasename} pint running",
            "finishStatusMessage": "${fileBasename} pint completed"
        }
    ]
}


output:
```
Run on Save is enabled
Running "php vendor/bin/pint app\Console\Kernel.php"
```

**Comment by d8vjork** [comment]
@serdartaylan Oh, this must be some missing thing, I'll check in a sec and release another pre-release version

**Comment by d8vjork** [comment]
@serdartaylan Ok, fix released in v1.0.1, tested on my virtual Windows machine now, seems working fine

**Comment by serdartaylan** [comment]
it didn't work on my computer. 

output:
["DEBUG" - 22:59:01] Formatting using command "php --config pint.json --preset laravel c:\Users\st\code\laravel\api\vendor\bin\pint c:\Users\st\code\laravel\api\app\Console\Kernel.php"
["INFO" - 22:59:01] Formatting completed in 472ms


command executed
`php --config pint.json --preset laravel c:\Users\st\code\ikame\api\vendor\bin\pint c:\Users\st\code\ikame\api\app\Console\Kernel.php`


commands should be like this
`php vendor\bin\pint --config pint.json --preset laravel c:\Users\st\code\ikame\api\app\Console\Kernel.php`
or
`php vendor\bin\pint --config pint.json --preset laravel app\Console\Kernel.php`

**Comment by serdartaylan** [comment]
it didn't work on my computer. 
If I had a problem the "runOnSave" command would not work.

output:
["DEBUG" - 22:59:01] Formatting using command "php --config pint.json --preset laravel c:\Users\st\code\laravel\api\vendor\bin\pint c:\Users\st\code\laravel\api\app\Console\Kernel.php"
["INFO" - 22:59:01] Formatting completed in 472ms

command executed
`php --config pint.json --preset laravel c:\Users\st\code\laravel\api\vendor\bin\pint c:\Users\st\code\laravel\api\app\Console\Kernel.php`

the code looks wrong.
`php --config pint.json --preset laravel vendor\bin\pint blabla....`

must be
`php vendor\bin\pint --config pint.json --preset laravel blabla....`



commands should be like this
`php vendor\bin\pint --config pint.json --preset laravel c:\Users\st\code\laravel\api\app\Console\Kernel.php`
or
`php vendor\bin\pint --config pint.json --preset laravel app\Console\Kernel.php`

**Comment by d8vjork** [comment]
@serdartaylan Ok thank you so much for the further debugging! Indeed, there was a problem with args order whenever they get in the way.

Problem solved in 1.0.2! Releasing

**Comment by serdartaylan** [comment]
It formats the file I saved. but when I click on "format document" menu, "Formatting completed in 427ms." I am getting the information but the file is not formatted.

The "format document" menu action isn't a big deal to me, but other users won't be affected if the issue is resolved.


my config
```
{
    "laravel-pint.enable": true,
    "laravel-pint.preset": "laravel",
    "[php]": {
        "editor.defaultFormatter": "open-southeners.laravel-pint"
    },
    "laravel-pint.enableDebugLogs": true,
    "editor.formatOnSave": true,
}
```

Thank you for the work.

**Comment by d8vjork** [comment]
@serdartaylan Can you send the full output? Issue is fixed on my side, I tried configuring the preset + having a `pint.json` on the root of my project on a Windows machine, this is the output I have:

<img width="1112" alt="image" src="https://user-images.githubusercontent.com/2331052/182825880-66aa660c-b3b0-49e1-ac77-b59c0851b3ab.png">

Also file's formatting whenever I save (with `editor.formatOnSave` toggled on) or triggered manually by the VSCode's "Format document" which are the same thing

**Comment by d8vjork** [comment]
I'll close, if any other issue please create a separate one as this was taking a different direction
