### ISSUE TITLE
Doesn't seem to work when application code is in a subdirectory

### ISSUE THREAD

**Issue by FrancisMawn** [open-southeners/vscode-laravel-pint#19]
Hi,

I've tried using your extension and couldn't get it to work in my current project. I'm not sure if it's relevant but my Laravel application code is stored in a **code** directory at the root of the project like so:
```
| azure
| code
   | app
   | bootstrap
   | config
   | ...
| docker
``` 
When I tried it on a brand new Laravel project it worked.

Also, I tried changing the configuration for the executable path to "./code/vendor/bin/pint" with no effect.

**Comment by d8vjork** [comment]
Thanks for the details. I'll take a look at soon as I can.

**Comment by tobidalhof** [comment]
I can't confirm this issue, configuring `laravel-pint.executablePath` in `.vscode/settings.json` works for me

```json
{
   "laravel-pint.executablePath": "./backend/vendor/bin/pint",
}
```

I'm on Windows using WSL2 and Devcontainers

**Comment by d8vjork** [comment]
Thanks @tobidalhof ! Anyway hope this still works in the next major release which is a full refactor to support multi workspace (pretty sure it will!)

**Comment by FrancisMawn** [comment]
I think we can close this as I can no longer reproduce the issue. Updating the executable path config to `./code/vendor/bin/pint` now works just fine.
