### ISSUE TITLE
Format On Save applying to workspace, not single file

### ISSUE THREAD

**Issue by adrum** [open-southeners/vscode-laravel-pint#21]
It appears running with the settings provided below, it formats the entire project, rather than the saved file. The output says it's running on a single file, but it appears to be running on the entire project. You can notice that elapsed time is pretty high. Running just the same command at the cli took 176 ms. Strangely the version reported is 1.0.1, but I just downloaded the project today, so the version bump may have been missed?

.vscode/settings.json
```jsonc
{
  "editor.formatOnSave": true,
  "laravel-pint.enable": true,
  "laravel-pint.enableDebugLogs": true,
  "laravel-pint.configPath": "api/pint.json",
  "[php]": {
    "editor.defaultFormatter": "open-southeners.laravel-pint"
  }
}
```
api/pint.json
```jsonc
{
    "preset": "laravel",
    "rules": {
        "braces": true,
        "not_operator_with_successor_space": false,
        "ordered_imports": {
            "sort_algorithm": "length"
        },
        "concat_space": {
            "spacing": "one"
        }
    }
}
```

Output: 
```log

["INFO" - 6:35:05 PM] Extension Name: open-southeners.laravel-pint.
["INFO" - 6:35:05 PM] Extension Version: 1.0.1.
["DEBUG" - 6:35:06 PM] Enabling Laravel Pint for workspace /project
"/project/api/vendor/bin/pint --config pint.json /project/api/tests/Feature/File.php"
["INFO" - 6:21:57 PM] Formatting completed in 899ms.
```

**Comment by d8vjork** [comment]
I thought about this as well, had a pretty similar thing but didn't know if it came from me or anyone else doing manually the CLI command under a project I've been working.

Good to know that I was wrong then.

Yes, latest is 1.0.2 (from the extension tho)

**Comment by d8vjork** [comment]
Releasing pre-release which fixes this, thanks again for the report!
