### ISSUE TITLE
Config path not correctly loaded

### ISSUE THREAD

**Issue by adrum** [open-southeners/vscode-laravel-pint#22]
The config file setting is not being passed to the pint command correctly. It appears to be using just the filename, instead of either the relative or absolute path of the config file. My laravel project is inside an `api/` folder in the workspace. Additionally, it seems like allowing any of the following paths should be acceptable:

- `/project/api/pint.json`
- `api/pint.json`
-`./api/pint.json`

It seems like the extensions should resolve the absolute command based on any of the above inputs and pass the absolute path of the file like the rest of the args.

.vscode/settings.json
```jsonc
{
  "editor.formatOnSave": true,
  "laravel-pint.enable": true,
  "laravel-pint.enableDebugLogs": true,
  "laravel-pint.configPath": "api/pint.json",
  "[php]": {
    "editor.defaultFormatter": "open-southeners.laravel-pint"
  }
}
```
api/pint.json
```jsonc
{
    "preset": "laravel",
    "rules": {
        "braces": true,
        "not_operator_with_successor_space": false,
        "ordered_imports": {
            "sort_algorithm": "length"
        },
        "concat_space": {
            "spacing": "one"
        }
    }
}
```

Output: 
```log
"/project/api/vendor/bin/pint --config pint.json /project/api/tests/Feature/File.php"
["INFO" - 6:21:57 PM] Formatting completed in 899ms.
```

**Comment by d8vjork** [comment]
Releasing in next pre-release version, thanks for the details!

**Comment by adrum** [comment]
@d8vjork I tried the latest pre-release today, but it's still not using my config file. Idk if the cwd isn't set properly, but it's definitely just using the default config. Below is the output from 1.1.0. I wonder if passing the config as an absolute path would make this more predictable, like the other segments of the command?

Additionally, it was only a slight increase in time spent. It would be nice if we could figure out a way to get this under 300ms when formatting a single file (or something close to when it's run manually via cli).


```
["DEBUG" - 7:41:13 PM] Config files found on workspace
{
  "workspace": "/project",
  "found": [
    "/project/api/pint.json"
  ]
}
["DEBUG" - 7:41:13 PM] Formatting file(s) using Pint
{
  "command": "/project/api/vendor/bin/pint --config api/pint.json /project/api/tests/Feature/File.php"
}
["INFO" - 7:41:13 PM] Formatting completed in 848ms.
```
