### ISSUE TITLE
Workspace settings being modified on every workspace opened

### ISSUE THREAD

**Issue by adrum** [open-southeners/vscode-laravel-pint#24]
I have a variety of project types I work with and this extension seems to automatically modify the workspace's `.vscode/settings.json` file. It's adding this line specifically:

```
"laravel-pint.enable": true
```

It would be nice to either:

1. Remove this functionality
2. Hide it behind a config option and set it in my user settings to not offer to modify my workspace settings every time I open a project.

**Comment by d8vjork** [comment]
Indeed can be troublesome, this was meant to maintain the simple "out of the box" of this extension, but might workaround this

**Comment by d8vjork** [comment]
Ok using global context for all now on v1.1.2 (pre-release)
