### ISSUE TITLE
Format on save problem when it's a workspace

### ISSUE THREAD

**Issue by danielprrazevedo** [open-southeners/vscode-laravel-pint#28]
**Something went wrong! Executable does not exists or lacks permissions.**

It's returning this message when I'm working in a vscode workspace.

I tried to reproduce the problem by opening in a regular window and it didn't happen, I noticed this only for the workspace.

When I use VSCode Command it is working fine, this was only noticed for format on save

My development environment is macOS and I use php by command line via asdf

**Comment by d8vjork** [comment]
Just to make sure: Are you using Pint globally or locally in your project? If so can you go to the "Output" tab of "Laravel Pint" and copy / screenshot of the command string trying to execute, remember to enable Debug Logs option in extension settings:

<img width="820" alt="image" src="https://user-images.githubusercontent.com/2331052/197503183-98e9ea87-6630-45d5-b3b5-cc7050c94c2e.png">

**Comment by sdmtt** [comment]
I'm having the same problem. Format on Save works fine if I open a single file, but does nothing when working inside a workspace.

Here's the output with debug enabled.

````
["INFO" - 9:39:29 PM] Extension Name: open-southeners.laravel-pint.
["INFO" - 9:39:29 PM] Extension Version: 1.1.2.
["DEBUG" - 9:39:29 PM] Config files found on workspace
{
  "workspace": "/home/santiago/Sites/project",
  "found": [
    "/home/santiago/Sites/project/pint.json"
  ]
}
["DEBUG" - 9:39:29 PM] Enabling Laravel Pint for workspace
{
  "workspace": "/home/santiago/Sites/project"
}
````

There's nothing added to the log when saving a file, but when calling the command manually the action is logged as expected.

````
["DEBUG" - 9:39:45 PM] Formatting file(s) using Pint
{
  "command": "/home/santiago/Sites/project/vendor/bin/pint --config /home/santiago/Sites/project/pint.json /home/santiago/Sites/go4audience.dev.local/app/Actions/Action.php"
}
````

---

I was able to get it working **inside** a workspace by setting Laravel Pint as the default formatter for PHP, like so:

![2022-10-28-21:29:54-screenshot](https://user-images.githubusercontent.com/69187/198753479-c7f46695-7ef9-42d7-b0b1-8d062015cfdf.png)

However, that setting will cause it to break **outside** a workspace, showing this error:

![2022-10-28-21:32:15-screenshot](https://user-images.githubusercontent.com/69187/198753787-f65e8a48-7726-4ced-9820-b588994bbd3b.png)

Will not work even if calling the format command manually. The log only shows the following:

````
["INFO" - 10:01:30 PM] Extension Name: open-southeners.laravel-pint.
["INFO" - 10:01:30 PM] Extension Version: 1.1.2.
````

Note: If it matters, I do not have Laravel Pint installed globally, only inside the project.

**Comment by jasonvarga** [comment]
I'm running into this issue, and I've narrowed it down to a couple of issues.

1. When you don't have a local pint installed, it returns early before the fallback to global logic has a chance to run.
	https://github.com/open-southeners/vscode-laravel-pint/blob/e94f7de380776f668e576760bcc74ed4ea40cfd7/src/ModuleResolver.ts#L32-L36

    But even if I just comment out that condition....

2. When you do `getWorkspaceConfig('fallbackToGlobalBin')` it returns `undefined`, and acts like you have configured it to _not_ fall back to the global binary.

	https://github.com/open-southeners/vscode-laravel-pint/blob/e94f7de380776f668e576760bcc74ed4ea40cfd7/src/ModuleResolver.ts#L42

	This is because `workspaceConfig` will return the `defaultValue` argument (undefined if you don't pass a second argument) if the value is configured the same as the default. (line 27)

	https://github.com/open-southeners/vscode-laravel-pint/blob/e94f7de380776f668e576760bcc74ed4ea40cfd7/src/util.ts#L18-L32

    There's currently no situation where `getWorkspaceConfig` will ever return the default value you've defined in `package.json`.

    `configByKey.defaultValue` should probably be returned on line 28 if `defaultValue` is undefined.

	

I'll try to put together a PR.

**Comment by d8vjork** [comment]
@jasonvarga Perfect! Will gladly accept it
