### ISSUE TITLE
Format on save not working in latest version v1.1.4

### ISSUE THREAD

**Issue by Quaap70** [open-southeners/vscode-laravel-pint#44]
Format on save doesn't work in v1.1.4. 
Switching back to v0.7.3 fixes this issue.

**Comment by d8vjork** [comment]
What's your config? Ensure you've enabled the extension on the config

**Comment by ashleyevans** [comment]
i'm seeing this too

confirming that installing v0.7.3 fixes the format on save

**Comment by Quaap70** [comment]
I had the same error with 1.1.4 as @bilogic with 1.1.2

["INFO" - 11:23:43 PM] Extension Name: open-southeners.laravel-pint.
["INFO" - 11:23:43 PM] Extension Version: 1.1.2.
["ERROR" - 11:23:59 PM] Executable not readable or lacks permissions for Laravel Pint.
["ERROR" - 11:24:00 PM] Executable not readable or lacks permissions for Laravel Pint.
["ERROR" - 11:24:04 PM] Executable not readable or lacks permissions for Laravel Pint.
["ERROR" - 11:24:08 PM] Executable not readable or lacks permissions for Laravel Pint.
["ERROR" - 11:24:15 PM] Executable not readable or lacks permissions for Laravel Pint.
["ERROR" - 11:24:48 PM] Executable not readable or lacks permissions for Laravel Pint.
["ERROR" - 11:26:04 PM] Executable not readable or lacks permissions for Laravel Pint.
["ERROR" - 11:26:14 PM] Executable not readable or lacks permissions for Laravel Pint.

**Comment by d8vjork** [comment]
This might get fixed by #45 (issue at #46)

Will merge it right away so you guys can test and tell afterwards

**Comment by d8vjork** [comment]
Probably solved in v1.1.6 (pre-release)

Closing if anybody still finds the same issue feel free to comment or reopen the issue

**Comment by Quaap70** [comment]
I just tested it briefly, but it seems to be working as it should. Thanks!
