### ISSUE TITLE
VSCode asking for conflict resolution

### ISSUE THREAD

**Issue by glaucomorais** [open-southeners/vscode-laravel-pint#47]
**Describe the bug**
Sometimes, more thant expected, VSCode asks me for conflict resolution.

**To Reproduce**
Edit a PHP file and save.

**Expected behavior**

**Screenshots**

**Environment:**
 - Operating system: Windows using Sail in WSL2
 - IDE / version: VSCode 1.83.1
 - Extension version: 1.1.4
 - Extension's config: { 
    "laravel-pint.enable": true,
    "laravel-pint.runInLaravelSail": true,
}

**Comment by d8vjork** [comment]
Will need more explanation on this as of where is that conflict

**Comment by d8vjork** [comment]
Will close this as explanation lack information to replicate this issue

Feel free to reopen with more info if anything else happens
