### ISSUE TITLE
[Feature request] Whitelist/blacklist file extensions or set to only PHP

### ISSUE THREAD

**Issue by sneakylenny** [open-southeners/vscode-laravel-pint#48]
When not in a composer project with pint the status indicator blinks with an error when navigating through files:

![pint-error](https://github.com/open-southeners/vscode-laravel-pint/assets/60601502/dc180f0c-4ee0-433b-800a-46287afa17f2)

Error log after navigating files:

![image](https://github.com/open-southeners/vscode-laravel-pint/assets/60601502/cdd32b8b-c59c-415e-8fd8-c082f352b919)

I wish I could disable the extension for certain file types or just non-php files altogether.

**Comment by d8vjork** [comment]
Good one! 👍  Open to PRs if urgent otherwise I'll leave it to after final v1 release

**Comment by d8vjork** [comment]
Now that I check this again, this could mostly be related to #43
