### ISSUE TITLE
High CPU usage

### ISSUE THREAD

**Issue by kossa** [open-southeners/vscode-laravel-pint#53]
**Describe the bug**
When I save a php file I got loading indicator and popup at the bottom

**To Reproduce**
Steps to reproduce the behavior: Not always happen, but when I save PHP file I got the issue

**Screenshots**
<img width="1012" alt="image" src="https://github.com/open-southeners/vscode-laravel-pint/assets/1175584/d4e243b3-7f50-412e-a49e-077914f49cf2">

![image](https://github.com/open-southeners/vscode-laravel-pint/assets/1175584/06e78b42-ea13-4c14-acc1-4cb5905a6a72)

**Environment:**
 - Operating system: Mac OS
 - IDE / version: 1.85.1
 - Extension version: v1.1.6
 - Extension's config: 
 ```json
"[php]": {
    "editor.defaultFormatter": "open-southeners.laravel-pint"
  },
"editor.defaultFormatter": "open-southeners.laravel-pint",
"laravel-pint.enable": true,
```

**Additional context**
I disabled the extension for 2 days I never had the issue

**Comment by horgolzari98** [comment]
It appears that you're encountering an issue with the Laravel Pint extension for VS Code when saving a PHP file. The symptoms include a loading indicator and a popup at the bottom.

Here are a few steps you can take to troubleshoot and potentially resolve the issue:

1. **Update Extension:**
   Ensure that you are using the latest version of the Laravel Pint extension. Extensions are regularly updated to fix bugs and improve compatibility.

2. **Check GitHub Repository:**
   Visit the GitHub repository for the Laravel Pint extension and check if there are any reported issues similar to yours. The repository may also contain information about recent updates or workarounds.

3. **Review Extension Configuration:**
   Examine your VS Code settings, especially those related to the Laravel Pint extension. Ensure that the configuration is set correctly and matches your preferences.

   ```json
   "[php]": {
       "editor.defaultFormatter": "open-southeners.laravel-pint"
   },
   "editor.defaultFormatter": "open-southeners.laravel-pint",
   "laravel-pint.enable": true
   ```

4. **Disable Other Extensions:**
   Temporarily disable other extensions to check if there is a conflict. If the issue disappears when the Laravel Pint extension is the only one enabled, re-enable other extensions one by one to identify the conflicting extension.

5. **Review VS Code Logs:**
   Check the VS Code logs for any error messages or warnings related to the Laravel Pint extension. You can access the logs by navigating to "Help" > "Toggle Developer Tools" > "Console" and looking for relevant messages.

6. **Check for Extension Updates:**
   Ensure that all your VS Code extensions, including Laravel Pint, are up to date. Sometimes, conflicts or issues are resolved in newer releases.

7. **Reinstall Laravel Pint:**
   If the issue persists, consider uninstalling and reinstalling the Laravel Pint extension. This can help resolve any potential corruption or misconfiguration.

8. **VS Code Stable Version:**
   Ensure that you are using a stable version of VS Code. While using Insiders or nightly builds can provide access to the latest features, they may also introduce bugs or compatibility issues with certain extensions.

If none of the above steps resolve the issue, consider reaching out to the extension's maintainers on its GitHub repository, describing the problem, and providing any error messages or logs you've collected. They may be able to offer more specific assistance or address the issue in a future update.

**Comment by d8vjork** [comment]
Can you try without extensions, only using Laravel Pint one?

I never have this issue on my computer but could be anything
