### ISSUE TITLE
Format on autosave not being applied

### ISSUE THREAD

**Issue by calebeso** [open-southeners/vscode-laravel-pint#54]
**Describe the bug**
The format on autosave mode its not being applied, even when Ctrl + Shift + P -> Format document using Laravel Pint 

**To Reproduce**
1 - Install latest version of the extension
2 - Extension settings
3 - Check enabled - Check Log debug - Check Run in Laravel Sail

**Expected behavior**
To format the file when saved or using the Ctrl + Shift + P option...

**Environment:**
 - Operating system: Linux Ubuntu
 - IDE / version: VsCode 1.85.0
 - Extension version : latest
 - Extension's config:
 
```
 {
    "laravel-pint.enable": true,
    "laravel-pint.enableDebugLogs": true,
    "laravel-pint.fallbackToGlobalBin": false,
    "laravel-pint.runInLaravelSail": true
}
```

**Additional context**
When I run directly through the command line with ./vendor/bin/pint it just works fine!

**Comment by bmalen** [comment]
Also not working on Windows. Possibly the same issue as https://github.com/open-southeners/vscode-laravel-pint/issues/52

**Comment by d8vjork** [comment]
This is because the Laravel Sail thing doesn't fully work. Related to #34

**Comment by d8vjork** [comment]
Closing because repeated issue, please track this on the other issue. If you think is not related go ahead and reopen this
