### ISSUE TITLE
doesn't work on Windows because of the drive letter Casing

### ISSUE THREAD

**Issue by mohamedyasser27** [open-southeners/vscode-laravel-pint#55]
**Describe the bug**
I installed the Laravel Pint extension in VSCode, and when I run it, the used command for formatting is wrong because it uses the lowercase letter when referring to the drive

The Command Used:
```
["DEBUG" - 1:58:18 PM] Formatting file(s) using Pint
{
  "command": "php vendor/bin/pint --config D:\\sanctum\\pint.json d:\\sanctum\\tests\\Feature\\ExampleTest.php"
}

```
**To Reproduce**
1. Install Laravel Pint extension in VSCode.
2. Open a Laravel project.
3. Run the extension on a test file.

**Expected behavior**
The generated command should use the correct casing for the drive letter(Uppercase) in the file path.

**Actual behavior**
The generated command uses lowercase for drive letter.

**Environment:**
 - Operating system: Windows
 - IDE / version: VSCode
 - Extension version : v1.1.6

**Comment by mohamedyasser27** [comment]
any Updates?

**Comment by balthild** [comment]
Well... It seems that the problem is not caused by the drive letter.

```shell
❯ eval "php vendor/bin/pint --config D:\\Projects\\PHP\\xxxxxxxx\\pint.json d:\\Projects\\PHP\\xxxxxxxx\\database\\migr 
ations\\2014_10_12_000000_create_users_table.php"

  ✓

  ───────────────────────────────────────────────────────────────────────────────────────────────────────────── PSR 12  
    FIXED   .............................................................................. 1 file, 1 style issue fixed  
  ✓ database\migrations\2014_10_12_000000_create_users_table.php                braces_position, statement_indentation  
```

`pint` do recognizes lowercase drive letters.

**Comment by d8vjork** [comment]
@balthild Does that PR resolve this issue then?

Sorry I haven't yet managed to have a Windows machine at my end

**Comment by balthild** [comment]
No. After converting the drive letter, it does still not formatting my files.

![图片](https://github.com/open-southeners/vscode-laravel-pint/assets/2662758/cec080a4-cb07-4b55-941f-116b58e60e95)

**Comment by balthild** [comment]
It seems like the pint command has never been executed actually. I tried seeing what the child process outputs, but got no logs...

![图片](https://github.com/open-southeners/vscode-laravel-pint/assets/2662758/cc1dbc95-97a6-4e2b-b6c4-2cba9eb829f9)

**Comment by balthild** [comment]
I found that the real problem is the CWD. 

https://github.com/open-southeners/vscode-laravel-pint/blob/acfa981a57855640272321c5b19a346171f06b70/src/ModuleResolver.ts#L50

Here the extension uses `.replace()` to get the CWD. On Unix-based OSes, this is fine. However, on Windows, the `executable` is `D:\path\to\project\vendor\bin\pint` but the `cmd` is `vendor/bin/pint`, making the `cwd` to be `D:\path\to\project\vendor\bin\pint`. This is not a directory, so it is not a valid CWD and the child process will fail to run in it.

**Comment by d8vjork** [comment]
@balthild Ah! That sounds more like a problem introduced in one of the latest releases (here d421f4b3c58fb2dc42c0096db084eaa06974088e)

**Comment by d8vjork** [comment]
I'll try that this doesn't affect Mac OS or Linux as well then will look forward to merge #57

**Comment by mohamedyasser27** [comment]
@d8vjork @balthild  Thanks  a lot it's working now
