### ISSUE TITLE
Not possible to install in WSL2

### ISSUE THREAD

**Issue by HassanZahirnia** [open-southeners/vscode-laravel-pint#6]
I'm trying `v0.2.1` and the install gets stuck when I try to install it in WSL2 (Ubuntu + W11). So basically can't use it cause it's disabled in workspace unless I manage to install it in remote WSL

**Comment by d8vjork** [comment]
That's problematic yeah as I don't use Windows, I'll try to look at my Parallels on Mac

**Comment by d8vjork** [comment]
Could be fixed with the path fixes of v0.5.0.

I'm closing this, but feel free to open it whenever you find this same issue again

**Comment by HassanZahirnia** [comment]
@Patabugen Hey buddy, thanks for letting me know. I just gave it a try again and the install process is working now 👍😄
