### ISSUE TITLE
onboarding recommendation

### ISSUE THREAD

**Issue by JeffBeltran** [open-southeners/vscode-laravel-pint#7]
First off thank you for creating this, much better setup than i had before. 

That being said, my recommendation is to keep the out of the box experience with this plugin as a "run pint". 

It took me a few mins to realize that the plugin was actually working, it was just using the `--preset psr12` flag

Plus chances are, if a user does have opinions on what they want to use they will likely already be using `pint.json`

**Comment by zepfietje** [comment]
Just ran into this as well, since Laravel Pint v0.2.0 changed the default preset back to Laravel.

**Comment by zepfietje** [comment]
Opened a PR to at least fix the default preset for now: https://github.com/open-southeners/vscode-laravel-pint/pull/8.

**Comment by JeffBeltran** [comment]
ah that would explain the decision to set that as default, i wonder if there is a way to refactor this to be more of an override, that way out of the box it works just like the binary would.

**Comment by zepfietje** [comment]
That's exactly what I suggested at the end of the PR:

> @d8vjork, maybe it's even better to leave out the --preset flag by default as @JeffBeltran suggested: https://github.com/open-southeners/vscode-laravel-pint/issues/7#issue-1284653040.

We could either remove the setting altogether, or add an `auto` option as default. Thoughts?

**Comment by d8vjork** [comment]
This is what I've discussed with @zepfietje on #4

They evolve quick! Enough to say I'm better thinking on a default option for everything which won't send any param if left as is (at least for the preset)

Its behaviour for the config will be the same, evaluating if workspace's folder have a pint.json on it, if so send it as param

**Comment by d8vjork** [comment]
@zepfietje voting for that auto one

**Comment by zepfietje** [comment]
@d8vjork, should we merge https://github.com/open-southeners/vscode-laravel-pint/pull/8 in the meantime as a quick fix to stick to the current Laravel Pint defaults?

**Comment by d8vjork** [comment]
@zepfietje I'll do it tomorrow as I'm away from the computer today

**Comment by d8vjork** [comment]
Closing this as for 0.4.0 release already improving all the "out of the box" stuff
